### ISSUE TITLE
`kmedians` function feedback

### ISSUE THREAD

**Issue by panntingg** [UBC-MDS/KMediansR#18]
Hi, I just sent a pull request of our second function - `kmedians`. Please review it @Jamienie .

**Comment by Jamienie** [comment]
Thank you for your work. This function works smoothly with the distance function. I just have one suggestion that maybe we can add a seed to keep results consistent.

**Comment by sreyaguha** [comment]
Hey! The function looks great!

In the Python part of this function, we modified the function to stop when there is no more updation of the medians and not run till `n_iter`. Maybe you could try and do that as that will decrease your computational time.

**Comment by panntingg** [comment]
Thank you for your suggestion!! I've edited the function.
