### ISSUE TITLE
`summary` function feedback 

### ISSUE THREAD

**Issue by panntingg** [UBC-MDS/KMediansR#22]
Hi, Fan~ I sent a pull request of the third function - `summary`. Please review it @Jamienie .

**Comment by Jamienie** [comment]
Thank you for your work. 
I have noticed that the 'rename' is not working properly. Maybe you can use different function, such as 'colnames'?

Thanks.

**Comment by panntingg** [comment]
Thank you, Fan!! `colnames` works well!!!
