### ISSUE TITLE
Milestone 01 feedback

### ISSUE THREAD

**Issue by hsmohammed** [UBC-MDS/KMediansR#25]
Hello,

Thank you for your milestone 01 submission. Great job! 
I just have some comments below,
- The folder containing the testes should be called `tests` instead of `test`.
- I suggest you use `roxygen2` for generating function documentations.
- In the `test_kmedians_summary.R", the "test if the reported Median Coordinates are correct" will always fail as the output should be a character not a vector
```
> typeof(summary(X = A, medians = m, labels = l)[1,2])
[1] "character"
```
Thank you!

**Comment by panntingg** [comment]
Thanks for your feedback!

We will change the folder name, edit the function documentation, and try to fix this testing.
